[package]
name = "cyberbard"
version = "0.2.0"
edition = "2024"

[dependencies]
eframe = "0.33.0"
egui = "0.33.0"
egui_alignments = "0.3.4"
image = "0.25.8"
lazy_static = "1.5.0"
rfd = "0.16.0"
rodio = "0.21.1"
serde = "1.0.228"
walkdir = "2.5.0"
